build_from:
  aarch64: ghcr.io/connum/debian-base-scansupport/aarch64:7.7.1
  amd64: ghcr.io/connum/debian-base-scansupport/amd64:7.7.1
  armhf: ghcr.io/connum/debian-base-scansupport/armhf:7.7.1
  armv7: ghcr.io/connum/debian-base-scansupport/armv7:7.7.1
  i386: ghcr.io/connum/debian-base-scansupport/i386:7.7.1