name: Scan Server
version: "1.0.12-dev"
slug: scan-server
description: Use your home assistant system as a scan server.
arch:
  - amd64
  - aarch64
usb: true
init: false
hassio_api: true
homeassistant_api: true
hassio_role: manager
host_network: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - share:rw
startup: services
options:
  filename_base: "scanserver"
  netshare_server: ""
  netshare_username: ""
  netshare_password: ""
  netshare_path: ""
schema:
  filename_base: str
  netshare_server: str?
  netshare_username: str?
  netshare_password: password?
  netshare_path: str?
